// Autogenerated at 20:18 Sat, 12 Oct 2024
//

import Foundation

public extension Localized {
    enum example {
        static var table: String { "example" }

        public static var example1: String {
            NSLocalizedString(
                "example1",
                tableName: table,
                bundle: bundle,
                comment: "Title")
        }

        public static var example2: String {
            NSLocalizedString(
                "example2",
                tableName: table,
                bundle: bundle,
                comment: "Description")
        }

        public static var example3: String {
            NSLocalizedString(
                "example3",
                tableName: table,
                bundle: bundle,
                comment: "Action")
        }

    }
}